# Generated by Django 5.1.5 on 2025-02-04 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='categoria',
            new_name='category',
        ),
    ]
